version: '3.8'
services:
  testenv:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./src/:/opt/project/src"
      - "./dataset/:/opt/project/dataset"
      - "./tmp/:/opt/project/tmp"
    tty: true